= After the Battle
:page-role: page=81

After the Battle of Five Armies, the remnants of the Goblin army
flee along the course of the River Running towards Mirkwood.
They are followed by the Elves and hunted down amongst the
forests – few escape the wrath of the Elves!

In this game, the Evil player chooses a force of Goblins, Wargs
and Wolf Riders. The Good player chooses an equal points value
of Elves. Note that the Good force can include some Elf cavalry.
Use the standard min/max for the size of game you are playing.

The Goblin side has Chieftains and Shamans as per the list, but
one less Chieftain than normally allowed. For this game, all Evil
character Command values are reduced by -1 – this will make
them quite slow and cumbersome compared to the Elves. The
Elves have the usual characters for a Good army, but note
that these are all Elves, including any Wizards.

Set-up the game with lots of patches of woodland or rocky
terrain that units will have to move around or through. You can
also represent the river along the length of the table if you wish,
but if you do so make sure you place a number of fords so that
units can cross from one side to the other.

The game is played along the length of the table rather than
across the width as usual. The Evil army deploys first along one
short edge. The objective for the Evil army is to move all the way
down the table and leave at the opposite edge. Any units that do
so are deemed to have reached safety. The Evil side will win if it
gets half of its total number of units to safety before they are
destroyed, or if the Elves are forced to withdraw first (unlikely!).
The Evil side has the first turn. The Good side deploys D6 units
onto the table at the start of their turn. The Good units deploy
onto the same short edge where the Evil army deployed. Good
units cannot be deployed touching Evil units. Good units that
deploy within 30cm of Evil units cannot move at all that turn.
Good units that deploy more than 30cm from an Evil unit can be
given commands as normal that turn.
