= The Edge of the Wild
:page-role: page=80

Whilst Thorin and his companions sleep under Beorn’s roof,
Gandalf, Beorn and some of Beorn’s human kin hunt down a
raiding party of Goblins from the Misty Mountains and their
Warg allies.

Set up the river sections from the Battle of Five Armies game
to represent a tributary of the great river Anduin – this becomes a
river that cuts off one corner of the table. Place a ford in the
middle of the river. The Citadel hill sections go together to make
a rocky promontory along one long table edge beside the river
and on the main part of the table (i.e., not inside the section cut-off
by the river). The remainder of the battlefield is lightly
wooded and can include the odd hill or areas of ruins.

The Evil side comprises Wargs, Wolf Riders and Goblins chosen
from the main Evil list. These set up on the table edge that
includes the promontory. The Goblins start off on the far side of
the river and will therefore have to cross the river to reach the
main battlefield. The Wargs and Wolf Riders start off around the
promontory.

The Good side comprises a single Wizard (Gandalf) and human
Heroes (hut no other characters). Troops can only be Giant Bears
or Men chosen from the Good army list (which means they will
mostly be Men).

Both sides are chosen to an equal points value and the game is
fought until one side withdraws when Victory Points are worked
out in the standard fashion.
