= The Elfking’s Gold
:page-role: page=82

Following the Battle of Five Armies, Dáin divides Smaug’s
hoard fairly between the Elves and Men. He sends wagon loads
of gold off to Laketown and the halls of the Elfking.
Unfortunately, the wagons are ambushed by marauding Goblin
renegades on their way to the Elfking – the Dwarf guard must
fight off the attackers and get the gold through!

For this game you will need a number of wagons – we'd suggest
three. These can be pieces of card cut to the standard base size if
you want, but you might be able to make something a little more
realistic or perhaps press another model into service (model
railway accessories do make nice scenic pieces, for examples).
The battle takes place on a battlefield that has numerous woods
and rocky areas, a few hills and a road that runs at an angle form
one side of the table to the other (about 160cm long).

The wagons are placed in convoy on the road and have to reach
the opposite table edge to escape. They can only travel along the
road. Wagons don’t move by orders, initiative or in any usual
way (e.g., drive backs or making way). Instead, wagons
automatically move along the road 10cm at the start of the Dwarf
Command phase and a further 10cm at the end of the Dwarf
player’s turn. Wagons cannot attack or fight and will stop 1cm in
front of any blocking units of enemy. If attacked, wagons have 3
hits each and Armour values of 4+. Wagons receive a bonus in
combat of +1, so if an enemy fails to score at all, the wagon will
always win. If wagons become embroiled in a larger
engagement, they still contribute their bonus. Wagons forced to
retreat are destroyed. Wagons that win a combat always stand.
Wagons cannot he driven back as a result of shooting.

The Dwarf players can only choose Dwarves apart from a
maximum of one Elf unit and one Elf character (sent by the
Elfking to escort the convoy). The Goblin player can choose any
number of Goblins, Wargs, Spiders and Hill Trolls, but must
include at least the usual minimums for all Goblin types.

The Dwarves win if they get more wagons off the table than the
Goblins destroy. The Goblins win if they destroy more wagons
than the Dwarves get off the table. If either side withdraws
before either condition is fulfilled, the winner is the side with the
most wagons destroyed/off the table. If both sides have the same,
the result is a draw.
