= The Goblin Kingdom
:page-role: page=81

Bolg marches down upon the Lonely Mountain and drives off
Thorin and his Dwarves before the Elves, Men or Dáin can
arrive. The tribes flock to join his ranks and he establishes a
mighty Goblin kingdom from which he launches devastating
attacks upon the Elves of Mirkwood, Men of Laketown
and Dwarves of the Iron Hills.

This is really an opportunity to use all of our Battle of Five
Armies characters and their special rules in huge Encounter Battle.
Such a battle can be fought on the fringes of Mirkwood,
with parches of woodland and rocks interspersed with streams. In
this battle, all the races of Middle-earth are united against
the evil Goblins and their foul minions.

Although no special rules are necessary for this game, it would
be interesting to divide the Good force into its constituent
elements and have them deploy at different times. For example,
Elves deploy in the first turn, but Men and Dwarves only arrive
on a dice roll – this will make the game more tense for the Good
player and it gives the Evil side a chance to wreak havoc before
the Good side can coordinate its troops. Oh – and if the Good
side includes Eagles, these should always arrive last of course…
it’s traditional!
