= The Battle of Five Armies
:page-role: page=6

[.edit]
[NOTE]
====
_The Battle of Five Armies_ was a Hobbit-themed edition of _Warmaster_.  Rules were very similar to _Warmaster Revolution_, but the game had its own army lists, spells, magic items and scenarios.
====

[quote,Bilbo Baggins]
While there’s life there’s hope!

For over two hundred years the former realm of the Dwarves
of the Lonely Mountain lay in ruins. Its people were
scattered, its lords reduced to the charity of their kinsfolk, and
its fabulous treasures gathered into the lair of the most terrible
of all living dragons. Smaug the Golden was his name and he
was a creature of immense age, stature and guile.

== The coming of Smaug

Smaug descended upon the Dwarf realm breathing fire and
destruction. He burned and flattened the town that lay about the
mountain and battered his way into the stone halls beneath.
Dwarves are dour folk who will not easily abandon gold
or home, but the flames and smoke drove them away. Many died
as they fled. The Dwarf King was one of those who escaped,
together with his son Thráin and young grandson Thorin.
Afterwards, Smaug gathered up all of Thrór’s treasure into the
largest of the underground halls at the root of the mountain.
Here he sat upon a bed of gold and slept the long sleep of
Dragons. The stench and fumes of his fire filled the Dwarf-hewn
chambers and spilled into the valley of Dale at the foot
of the Lonely Mountain. All about, the land lay blackened and
burned and became known as the Desolation of Smaug.

== The thief Baggins

So things remained for a long time until Thorin Oakenshield,
son of Thráin, came back to the Lonely Mountain to recover his
grandfather’s treasure. With him were twelve Dwarf
companions and kinsmen. These were accompanied by the
wizard Gandalf and the thief Bilbo Baggins, a Hobbit from the
distant land of the Shire. It was Bilbo who discovered a secret
passage into the Dragon’s lair. By this means he stole a golden
cup from the hoard and inadvertently aroused Smaug from his slumbers.
Enraged to discover that his lair had been violated
whilst he slept, Smaug issued forth from under the mountain
and scoured its slopes for the impudent thief. After finding and
eating the ponies and provisions belonging to Thorin and his
companions, Smaug flew to nearby Laketown. The cunning
Dragon had rightly surmised that his tormentors had obtained
aid and supplies from the men that dwelt there. Whilst he had
little notion exactly how the men of Laketown were involved,
he did not feel inclined to remain idle whilst thieves conspired
to steal his treasure (or worse).

So Smaug the Golden met his end. At Laketown he was slain
by Bard, son of Brand, whose keen arrow found the only bare
and vulnerable spot in the Dragon’s scaled and gem encrusted
breast. With his heart pieced, Smaug’s huge corpse fell from
the sky into the lake, but not before he had burned and
destroyed Laketown and slain many of its people as they ran
before his wrath.

== The armies gather

Thus was set the scene for one of the greatest battles ever
fought in the north of Middle-earth, The news of Smaug’s
death soon reached the ears of the Elfking of Mirkwood and
spread far and wide throughout the lands thereabouts. Warriors
were quickly mustered and began the march upon the Lonely
Mountain. It was supposed that the treasure lay unclaimed and
unguarded – no one knew about Thorin and the Dwarves. The
Elfking led his warriors east from Mirkwood. Bolg, greatest of
the Goblin warlords of the north, drove his army south. Bard
led men from Laketown to the north. Meanwhile the Dwarf
Lord Dáin marched his armoured warriors westward from their
home in the Iron Hills. Only Dáin knew that Thorin had taken
possession of the treasure, and as Thorin’s cousin he was
honour bound to come to his assistance.

Meanwhile Thorin and his band of treasure hunters had
established themselves in the mountain and fortified its gate –
for they had no intention of sharing what they regarded as their
treasure. The sight of all the gold and the prospect of
reclaiming his grandfather’s lost realm had hardened Thorin’s
heart.

When the Elfking’s warriors and Bard’s men met they made
common cause and petitioned Thorin for a share of the
treasure. Thorin stubbornly refused to treat with them. He
would not even listen to the pleas of Bard who had in fact slain
the Dragon, whose town had been destroyed, and whose people
were now homeless and starving as a result. As Thorin saw it,
he had only to await the arrival of Dáin to avoid all claims upon
his hoard. He reasoned that once his kinsfolk were beside him
he would be able to hold out against even the most determined
enemy. When Dáin did arrive, the Elves quickly deployed to
prevent the Dwarf army joining forces with Thorin. At first it
appeared a battle was inevitable, with Men and Elves on one
side and Dwarves on the other. However, just then something
happened to completely change things.

== The Battle of Five Armies

Whilst Dáin had marched steadily westwards, a huge army of
Goblins and Wargs (ferocious and evilly intelligent wolves)
had been marching from the north. As Dáin arrived at the
Lonely Mountain he was not to know that an entire Goblin
army was already hard upon his heels. It was therefore
fortunate that just as Elves and Dwarves raised spears and axes,
the outriders of the Goblin army burst upon them. Whilst Dwarves
and Elves bear little love for each other this is, of
course, nothing compared to their loathing of the foul Goblin
race. A council of war was immediately called between the
leaders of Men. Elves and Dwarves. The three now allied
armies quickly deployed upon opposing spurs of the Lonely
Mountain to await the onslaught of the forces of Bolg
the Goblin Chieftain. The battle that followed was known ever
afterwards as the Battle of Five Armies – Dwarves, Elves and
Men on one side and Goblins and Wargs on the other.

This is, of course, but a bald summary of the events which can
be read in their entirety in the concluding chapters of The
Hobbit by JRR Tolkien and with which, I'm sure, most
readers are already familiar.
