= The Ruin of Esgaroth
:page-role: page=81

The Dragon Smaug flies to the Laketown of Esgaroth in a rage.
He attacks the town and sets fire to it, swooping down upon the
poor inhabitants slaying and burning then as they flee. The men
of Laketown defend their homes as best they can, but the Dragon
is a formidable and angry foe!

Laketown lies beside the Long Lake and has been partially
destroyed by Smang, so start with a ruinous settlement by the shore
of a large like. Smong’s objective is to destroy the town so we shall
say that Smang wins if he breathes fire on any of the town’s
building causing a grand total of ten hits. As Smaug can cause a
maximum of three hits each time he breathes fire, this means he
will have to do so at least four times – more probably five or six.

The Men have four units of Archers and four units of Spearmen.
The character Bard is the General and there is another character,
the Master of Esgaroth, who is weak and indecisive so we shall
give him a Command value of only 7. Because they are fighting
for their homes, the Men of Laketown will not withdraw unless
Bard is slain. Smaug wins if he burns Esgaroth or slays Bard.
The Men win if they slay Smaug.

*Special rule:* Roll the dice separately for Bard’s shooting – if he
rolls a 6, he scores three hits automatically without any Armour
Save for Smaug.
