= Scenarios
:page-role: page=80

The Battle of Five Armies is an example of what we call a
scenario. A scenario is nothing more than a game that is based
around a story or series of events. In our case, these are events
taken from, or inspired by, _The Hobbit_. Inventing your own
scenarios is part of tabletop gaming – it gives everyone a chance
to use their own imagination to create a challenging and
enthralling game. Designing scenarios that are a challenge to
both sides yet fairly balanced is key to making a good idea work,
but don’t expect to get everything right first time. Creating good
scenarios that are enjoyable for both sides to play is quite a feat –
but that’s no reason not to try.

The following are typical ideas for scenarios and serve as
examples of how players might expand the types of battle
played. They are not complete or definitive examples of
scenarios – that would fill another book as long as this one – but
we hope to include new scenarios as part of our Great Battles of
Middle-earth website.

== Designing scenarios

When inventing a scenario, it’s always best to keep things
simple. One special rule or twist is usually enough to make a
game substantially different. The more complex you make a
scenario and the more special rules you invent, the greater the
likelihood that things won’t work out as you expect. When
inventing rules for scenarios I always say to myself ‘What’s THE
rule for this scenario?’ and then try to avoid adding too much
else. Good ideas can always be used in new scenarios after all.

It is always a good idea to play both sides of any scenario you
have invented otherwise it’s all too easy to invent a game that’s
fun for one side but frustrating or dull for the other. Playing both
sides gives you a better perspective on the game as a whole.

Always try to make scenarios winnable for both sides – but don’t
worry if you can’t make things exactly even. If you want to play
a perfectly fair game then play an Encounter Battle – scenarios
are about doing things differently. Sometimes that might mean a
game is easier for one side to win than the other – so be it. You
can always play twice – once with either side – and compare
overall results to establish the true winner.

There are several useful ways to even up a game or make it more
balanced. The points values ensure that armies are roughly
comparable in fighting value. This works well in most situations,
but in some scenarios certain kinds of troops will sometimes
prove more or less useful depending on circumstance. For
example, if a game takes place in a forest, cavalry will prove
much less useful than they would in a game on an open plain.
Points values can’t be perfect for every situation. As scenario
designers we can get round this by specifying troops for a
scenario or limiting choices from the army lists.

Another way of altering game balance is by changing the usual
withdraw levels so that more or fewer units are lost before one
side withdraws. For example, because Dwarves are especially
dour and stubborn and love gold you might decide that a force
made up of Dwarf gold prospectors has a withdraw level of 75%
of its units rather than 50%. Of course you could dispense with
the withdraw level entirely and fight for a fixed number of turns
or until some special objective has been reached – for example
until a specific unit reaches a predetermined point on the
battlefield.

It is very important to describe exactly how the game ends and
how players score Victory Points (VPs). Both sides will work
towards these objectives during the game. The usual method for
working out VPs provides a good basis for most games, but you
might want to award extra VPs if one side accomplishes a
predetermined task. For example, if the objective is to escape
from the table with a wagon full of treasure then the game might
end as soon as the wagon leaves the table and the player could
earn an extra 100 VPs.

Write things down! This should be obvious but it’s surprising
how hard it is to read hastily made notes once a battle is over.
Make notes during the game and write down suggestions to
consider later. Once you are happy with your scenario, write it up
property and include an accurate map – that way you can play
again or swap scenarios with other players if you want.

Remember that the most important thing is to enjoy your
gaming, if you invite another player to take part in a scenario that
you have invented, don’t be too defensive about comments or
suggested changes. Designing games is teamwork – never be
afraid of pooling ideas and using the best. Similarly, if you are
playing a scenario invented by another player don’t be too ready
with alternative ideas of your own; your role is to try and help
the designer realise his ideas not to press for your own. Most
importantly, always analyse things from as a dispassionate point
of view as you can. Try and figure out why things work out or
feel a certain way when you play.

== Some scenario plans

Here are some outline plans for different scenarios inspired by
the characters and places described by JRR Tolkien in
_The Hobbit_. They are not complete games by any means – that
would require far more space that we have within this book.
These plans will hopefully inspire at least a few players to have
a go at working up their own scenarios and hopefully we will be
able to compile the best examples onto our website.
