= Swords in the Dark
:page-role: page=81

Goblin marauders continue to plague the wilds for years. Mostly,
they attack at night to avoid the cruel light of the sun, which all
Goblin-kind hates. In this battle, a force of Goblin bandits comes
across the night revels of the Elfking and springs an ambush
upon the feasting Elves.

In this game, both sides have the same points value – we’d
suggest 1,000 points a side but it’s not critical. The tabletop
represents part of the forest of Mirkwood and has patches of
woodland interspersed with hills, rocky areas and perhaps the
odd stream. In the centre of the table is a clear area roughly 40cm × 40cm –
this is where the Elves are feasting. The entire Elf force
is deployed into this area at the start of the game. The Goblin
force is deployed once the Elves are in position. Evil units can be
placed anywhere on the table but no units can be placed within
30cm of any Elf units.

The Good side can only choose Elves (you might allow a limited
number of Men or Dwarves as guests!). The Evil side can choose
any units from the Evil army list apart from Smaug. The Evil
force must include at least as many Goblin infantry units as it has
other units combined (i.e., at least half must be Goblin infantry).

The game takes place at night, so all movement distances are
reduced to infantry pace (20cm), even flyers if the Evil force
includes Bats. Visibility is restricted to a maximum of 20cm.
This will effect bow ranges, for example.

At the start of the game, the Elves are feasting and unprepared to
fight. Until an Elf unit has been given a successful order, it is
therefore rated as ‘unprepared’. Unprepared units cannot be
included in brigade orders (they have to be given orders
individually), cannot shoot and will not pursue if they win a
combat. As some units will be ready to fight whist others remain
prepared, it’s a good idea to devise a marker to indicate
‘unprepared’ status – a coin or piece of coloured card will do.

Fight the game until one side withdraws as normal and then work
out Victory points. As the Goblins have the advantage of
ambushing the Elves, the Good side starts off with a 100 pts VP
bonus. This means the Goblins will have to destroy at least two
units of Elves whilst they are unprepared to even up the score.
