=== Ball of Flame

[.cost]#5+ to cast# [.points]#Range 30cm#

_A ball of flame shoots form the Wizard’s outstretched arm
burning all in its path._

Draw an imaginary line 30cm long from the Wizard’s stand
in any direction you wish. The line will pass through any
intervening units but not beyond terrain that would normally
stop a missile shot, e.g. over the crest of a hill, more than 2cm of
woodland, and so forth.

Each unit under the line takes three shooting attacks worked
out in the usual way. Note that this spell can easily affect
several units and will affect all units that fall beneath the line
(including your own). Unengaged units can be driven back
by a Ball of Flame as with ordinary shooting (even including
friends). Engaged units cannot be driven back by the Ball of
Flame but carry over any hits scored into the first round of
combat; any hits scored count as having been struck in the
combat itself.

=== Voice of Command

[.cost]#5+ to cast# [.points]#Range 30cm#

_The Wizard’s voice booms out across the battlefield directing
troops above the tumult of combat with the magical Voice of
Command._

The spell can be cast on any unengaged friendly unit within
range regardless of whether the Wizard can see it or not. The
spell affects only a single unit, never a brigade and there is no
supporting charge possible.

The unit can be moved just as if it had received an order in the
Command phase. Character stands that have joined the unit
will not move with it: they remain where they are.

=== Weird Enchantment

[.cost]#4+ to cast# [.points]#Range 30cm#

_A weird enchantment forms around the target unit and engulfs
it in strange lights, scary nightmares and disorientating special
effects._

This spell can be cast on any enemy unit within range regardless
of whether the Wizard can see it or not. The spell lasts until the
end of the opposing player’s following turn.

The unit moves at half pace in all situations: even when charging
for example. The unit counts all enemies as terrifying (−1 Attack
penalty) even when it is otherwise immune to terror. If the unit
would normally cause terror then it ceases to do so and counts
all enemies as terrifying just like everyone else. However,
if the target is Undead or Daemon it will not count enemies
as terrifying although all other penalties apply as described
(Undead and Daemons are hard to spook).

=== Teleport

[.cost]#2+ to cast# [.points]#Range N/A#

_With a swirl of his cloak, a crack of thunder and just a hint of
maniacal laughter the Wizard vanishes to reappear anywhere
on the battlefield._

The Wizard is moved to a new position anywhere on the table.
He can leave or join a unit if he wishes, enabling a Wizard
to move into or out of combat for example. Once the Wizard
has moved he can cast a second spell, but note this must be
a different spell and not a further Teleport! Roll to cast the
second spell as normal. A Wizard that Teleports successfully
can therefore potentially cast two spells that turn.
