= Introducing Warmaster

Warmaster is a game of conflict on a grand scale,
fought over an area of ground that we might
imagine to be many miles square. Although our models
are approximately 10mm high this should not be taken as
a literal representation of scale when it comes to the size
of the battlefield.

The area occupied by a regiment of models is assumed
to encompass hundreds of warriors including all of their
supporting elements such as mules laden with spare
ammunition, surgeons’ wagons, preachers, servants,
messengers, scouts and all the paraphernalia of warfare.
Never mind that the actual number of warriors depicted
is typically about 30-40 in the case of an infantry
regiment – we must imagine the formation whole and
glorious as it marches to battle! This abstraction, by
which a few models are taken to represent many more
actual warriors, shouldn’t concern us too much during
play, although it has a direct bearing on the way the rules
have been formulated.

Similarly, when considering the distances moved by our
troops it is wise to think of a standard move of 20cm
or 30cm as representing a unit redeploying into a new
position from which it is able to launch attacks or push
groups of warriors forward to shoot, skirmish or scout
ahead. Where troops charge their enemies it would be
inappropriate to imagine them running hell for leather
over this entire distance – rather, they march into
position, deploy their ranks appropriately and cover
only the very final part of their manoeuvre at anything
like a hurried pace. Hence, movement distances in
Warmaster are dependent upon a unit’s deployment and
command structure rather than on the notional speed of
an individual warrior.

Because Warmaster units represent such large bodies
of troops, the rules for combat emphasise the position
of units rather than the weapons with which individual
warriors are armed. Troops that are in advantageous
terrain or supported by friends obviously fight more
effectively. Even poor quality troops will fight relatively
well in these circumstances. On the other hand, casualties
suffered have a direct bearing on a unit’s effectiveness,
not only making it weaker in combat but also eroding
its logistical support, making it harder for the general to
direct as he wishes.

A comparable approach has been taken to missile
ranges. In the game, a bow can shoot as far as 30cm but
this represents a longer distance than a bow could really
shoot. This distance is not based on the range of a bow
but the tactical area that a missile armed regiment is able
to cover. We might imagine the regimental commander
sending individual detachments forward or edging the
line to and fro to entice the enemy to their doom! For this
reason missile ranges are not based entirely on theoretical
weapon ranges – we are interested in the much broader
ability of a missile-armed regiment to dominate the
ground in front of it.

The most important aspect of the game is the role
allotted to the armies’ commanders. Warmaster is based
around the ability of generals and their subordinate
commanders to control the action around them. In the
game this is accomplished by dice rolls but in reality we
might picture the general and his staff bent over maps,
eagerly awaiting word from their subordinates, reading
reports of distant fighting and dispatching messengers
with fresh orders. Generals influence the action around
them by directing troops – their role as combatants is
not especially significant – although a commander’s
immediate presence can inspire troops to that extra bit of
effort at critical moments!

== The Game Rules

The following pages contain all the rules for the
Warmaster game. We suggest that you read through
them before attempting to play but don’t worry about
trying to learn the game by heart. It’s far better to get
stuck in! You can always check out the rules as you go
along. After a few games you’ll find the basic routines
are easily remembered whilst more unusual rules can
be looked up as required. The rules are presented with
summaries at the beginning of each section.

== Dice

The Warmaster game uses dice to represent the chance
element of shooting and close combat. To save space we
refer to an individual six-sided dice as a ‘D6’. So when
we instruct you to roll a D6 we are simply asking you to
roll a dice.

Sometimes you’ll be required to roll two dice and add
the scores together, in which case we will ask you to roll
‘2D6’. Occasionally, you will need to roll one dice and
multiply the score by another number, in which case we
write this as 10 × D6, or 5 × D6 and so on.

In a few instances the rules will also ask you to roll a
‘D3’. This is simply a convenient way of referring to a
random roll of between 1 and 3 achieved by rolling a
normal D6 and halving the score rounding up. So, a D3
roll of 1-2 = 1, 3-4 = 2, and 5-6 = 3.

= Rulers & Tape Measures

In the Warmaster game, units move across the battlefield
by a measured distance. When troops shoot it will be
necessary to measure to ensure that they are in range. All
distances are given in centimetres. We recommend that
players purchase one or more retractable tape measures
for measuring distances.

Players who prefer to play using inches can do so by
halving the value of all the distances given. This gives
slightly longer moves and ranges but makes no practical
difference so long as both sides use inches.

= Get stuck in

Although the scope and pageant of the game can only
be realised by playing with miniature armies, for
the purpose of learning the rules you might want to
improvise by making your own troop stands from card.
This will enable you to get a feel of how the game works
right from the start.

Similarly, you may want to field unpainted models that
you buy. You can paint your army later but this will take
time so it’s best to learn the game and fight a few battles
first.

Nothing else is needed, though a pen and paper are
useful for making notes and a nice hot cup of tea is
always a good idea!
