= Advanced Terrain Rules

The Advanced Terrain Rules are meant to widen the variety of terrain possibilities so players may
spice up their battlefields with different terrain types.

*Hills/Slopes.* Impose no penalties on the movement of
troops. All units can move over hills and slopes so long as
they are not especially steep, rugged, or otherwise difficult
– such features must be stated before the game. Overall
footprint of the hill models, including slopes block line
of sight. Infantry and artillery stands positioned on a hill
are xref:combat-phase.adoc#defended[defended] against any units charging or shooting from
lower positions.

*Shallow rivers/Streams.* This terrain only blocks the
movement of Chariots and Artillery/Machines. Infantry
can be xref:combat-phase.adoc#defended[defended] along the river’s edge against enemy
charging from within or across a stream. Streams and
shallow rivers don’t block line of sight.

*Broken/Marshy Ground.* This includes areas that are
hard going for whatever reason; for example: treacherous
ruins, entangling scrub, irrigated or excessively muddy
fields, soft marshy ground. This terrain type counts as
dense and doesn’t block line of sight. Infantry stands are
xref:combat-phase.adoc#defended[defended] in broken/marshy ground.

*Loose Terrain.* Cultivated fields to sand dunes. Rocky
ground to fully grown corn fields. This terrain doesn’t
necessarily give a defender any advantages, but it isn’t
going to do anything to help the chargers advance.
Charging units earn no charging bonus when charging
a unit within loose terrain. It is also impenetrable to
Chariots and Artillery/Machines. Loose terrain doesn’t
block line of sight.

*Woods and Tall Scrub.* These consist of substantial
areas of growing trees or tall vegetation. Only Infantry
can enter it and stands count as xref:combat-phase.adoc#defended[defended] when within.
Woods and Tall Scrub are dense terrain with visibility
of 2 cm.

*Villages/Cities and other Built-Up Areas.* Distinguishable
bordered area consisting of a number of buildings. They
will typically have paths and dividing walls as well as
areas of garden, pasture, orchards and so forth. The
entire built-up area is considered to be a broad terrain
type: no account is taken of individual buildings, gardens,
and so forth. All units can enter it, infantry and artillery
units count as xref:combat-phase.adoc#defended[defended] when within. All units
can be pursued when starting their retreat in this terrain
type. Villages/Cities are dense terrain with visibility of
2 cm.

*Individual Buildings/Terrain Features.* These are
significant sight. structures or even densely packed or
connected clusters of individual buildings or terrain
features such as sole rocks. These are impenetrable to all
units and block line of sight.

*Rivers/Lakes and other Deep Water.* These are
impenetrable to all units and don’t block line of sight.

*Ravines/Deep pits.* These are impenetrable to all units
as might reasonably be expected. This type of terrain
doesn’t block line of sight.

*Sheer Cliffs and Mountains.* These are impenetrable to
all units as might reasonably be expected and they block
line of sight.

*Roads and Tracks.* These permit movement to units in
column formation as for open ground regardless of the
type of terrain traversed. A base placed centrally across
or along a road is conveniently assumed to be travelling
along it despite the road’s width. Infantry placed on a
road through dense terrain still count as ‘xref:combat-phase.adoc#defended[defended]’
stands – other troop types count as ‘in the open’ as usual.
If a unit moves its entire distance along a road then the
next order will be issued with a +1 to command. Roads
obviously don’t block line of sight.

// Spelling i.e.
Some players may prefer to move their infantry in
marching column along the roads in the same way
as cavalry i.e. short edge to the front. This is perfectly
possible and the 20cm can be treated as the ‘front’ for
the purpose of moving and sight, however it still counts
as side when being in combat with all the consequences.

// Spelling bridges
*Bridges and Fords.* If a river or ravine has a bridge then all
troops can cross at that point without penalty. Similarly,
if a river has a ford, all troops except Chariots and
Artillery/Machines may also cross at the ford without
penalty. Bridges and fords don’t block line of sight.

*Low Linear Obstacles.* These are features such as ditches,
hedges, fences, and low walls primarily intended to form
property boundaries, divide fields or confine animals.
Low linear obstacles impose no restriction or penalties
on the movement of Infantry, Cavalry or Monsters, but
cannot be crossed by Chariots or Artillery/Machines.
Infantry and artillery stands placed behind a low linear
obstacle count as xref:combat-phase.adoc#defended[defended]. Low linear obstacles don’t
block line of sight.

// Spelling defence
*High Linear Obstacles.* These are tall features such as
high walls and hedged, fenced or ditched embankments
primarily intended for defence. These features are
impenetrable to all troops except for infantry. Infantry
can move over or through a high linear obstacle without
penalty. Infantry and artillery stands placed behind
a high linear obstacle count as ‘fortified’. High linear
obstacles block line of sight.

*City and Fortress Walls.* These can be found in detail in
the chapter xref:siege-and-fortresses.adoc[Siege & Fortresses].
