= Game Sequence
:page-role: -toc at-a-glance

[cols="^1,<4,<4,<2",frame=none,grid=rows]
|===

a|
[discrete]
== 1
a|
[discrete]
=== Deploy Armies

At the start of the battle both players line
up their armies at least 80cm apart.
|Armies are deployed secretly by making a map of the
battlefield with the positions of units indicated or, if
players prefer, by placing one unit at a time, starting
with the player whose army has the most units.
|

a|
[discrete]
== 2
a|
[discrete]
== Commence Battle

Each side takes a turn one after the other,
starting with the player who rolls the
highest score on a D6.
|
|

|
|A turn is divided into three phases,
as shown below. These phases are
completed in the order shown, starting
with the Command phase and ending
with the Combat phase.
|Players can either set a number of turns to play or fight
until one side is forced to withdraw.
|See xref::end-of-the-battle.adoc[].

|
a|
[discrete]
==== Command

[.bo5a]#Troops are moved#
|The player whose turn it is [.bo5a]#can move his forces in the# Command phase
Command phase. [.bo5a]#Units# can either move on their initiative or in
response to orders as they receive them.
|See xref::command.adoc[].

|
a|
[discrete]
==== Shooting

Troops shoot with missile weapons.
|The player whose turn it is can now direct missile fire.
Shooting includes short-ranged weapons such as bows,
as well as longer ranged weapons like cannons, and
magic spells. Often these will be out of range of the
enemy, so there will be no shooting that turn.
|See xref::shooting.adoc[].

|
a|
[discrete]
==== Combat

Both sides fight hand-to-hand combat.
// Deleted "After shooting is complete, the players work out any hand-to-hand combat."
|In the Combat phase both sides
fight. This phase is a bit different to the other phases
because it is not just the player whose turn it is that
takes part. In the Combat phase both players fight with
all their troops that are engaged.
|See xref::combat.adoc[].

a|
[discrete]
== 3
a|
[discrete]
== The Battle Ends

The game finishes when one player
concedes defeat or an army is forced to
withdraw from the battle or, if players
prefer, when an agreed number of turns
have passed.
|Once a player has completed his Combat phase his turn
is over and it’s his opponent’s turn. His opponent then
takes a turn in the same way, starting with Command
and ending with Combat. It is then the first player’s
turn again and so on until both players have completed
the predetermined number of turns or until one side
concedes defeat or is forced to leave the battlefield.
|See xref::end-of-the-battle.adoc[].

a|
[discrete]
== 4
a|
[discrete]
== Hail the victor!

Once the game is over and the dust of
battle settles, it is time to work out who
has won.
| Once the battle is over, both players add up the number
of victory points they have scored. The more enemy
units they have destroyed, the more victory points they
will accrue.
|See xref::end-of-the-battle.adoc[].
|===
