= Movement at a Glance
:page-role: -toc at-a-glance

== Distance

. Units move in the Command phase either by initiative or if they receive orders.
. Units receiving one order after another are able to move [.ancients]#up to three# times during the
  Command phase.
+
[cols="<,^,^",frame=none,grid=rows]
|===
|Types |Full Pace |Half Pace

|Infantry |20cm |10cm
|Cavalry |30cm |15cm
|Chariots |30cm |15cm
|Artillery |10cm |5cm
|Monsters |20cm |10cm
|Machines 2+| Movement distances vary
|Flying Units |100cm |10cm
|Characters |60cm |60cm
|===

. Charging units and evading units move at up to full pace. [.bo5a]#Units in# regular formations
  of columns or straight lines move at up to full pace unless fortified.
  Fortified units and units in an irregular formation move at up to half pace.

== Terrain

////
// WMR original. Note incorrect — cavalry can enter villages, loose terrain
. Infantry can move into any terrain.
. Cavalry and monsters cannot move into or over terrain features other than hills,
  bridges, shallow fordable rivers and low obstacles.
. Chariots, artillery and machines (in general) cannot move into or over terrain
  features other than hills and bridges.
////

// Inspired by Bo5A, but that has different rules.
[.edit]
[%header,format=tsv,cols="h,3*<",frame=none,grid=rows]
|===
include::partial$terrain-restrictions.tsv[]
|===
